### ISSUE TITLE
build

### ISSUE THREAD

**Issue by caffeine239** [barncastle/Alpha-WoW#1]
is this only for alpha? what about updating to 1.12.1? are you done with this project?

**Comment by barncastle** [comment]
The point of this project was to support the earliest WoW client build available (0.5.3) and give people the ability to explore more than what the existing sandboxes provided - and to learn something along the way.

1.12.1 has already been done and to a really high degree by the two Mangos teams; I'd suggest looking at their cores.

**Comment by caffeine239** [comment]
well i have taken this and tryed porting to 1.12.1,  any idea how i go about the object updates for it?? Cant get world login.

**Comment by barncastle** [comment]
There are going to be quite a few things that need changing. Off the top of my head:
- Update fields (look at Mangos source)
- Opcodes (look at Mangos source)
- Update mask (might not have changed)
- Around patch 1.3 the packets at both end were encrypted

Also a large amount of the packet structures will be different.

**Comment by caffeine239** [comment]
Yes I understand all that.  I know for sure it's in the object update tho. 

Update fields (look at Mangos source) <<-- Done
Opcodes (look at Mangos source) <<-- Done
Update mask (might not have changed)<<-- Not sure about this one?
Around patch 1.3 the packets at both end were encrypted <<-- Done
